stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: ops_docker
    
test:
  stage: test
  script:
    - echo "TEST"

build:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: dockerdaemon  
  variables:
    # Tell docker CLI how to talk to Docker daemon.
    DOCKER_HOST: tcp://dockerdaemon:2375/
    # Use the overlayfs driver for improved performance.
    DOCKER_DRIVER: overlay2
    # Disable TLS since we're running inside local network.
    DOCKER_TLS_CERTDIR: ""
  script:
    - ls -al
    - docker container ls -a
    - docker build -t $IMAGE_NAME .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push $IMAGE_NAME
    - docker images

deploy:
  stage: deploy
  image: docker:latest
    - name: docker:dind
      alias: dockerdaemon  
  variables:
    # Tell docker CLI how to talk to Docker daemon.
    DOCKER_HOST: tcp://dockerdaemon:2375/
    # Use the overlayfs driver for improved performance.
    DOCKER_DRIVER: overlay2
    # Disable TLS since we're running inside local network.
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker container ls -a
    - docker container rm -f $IMAGE_NAME
    - docker run -d -p 8001:8001 --name docker-proj --restart always $IMAGE_NAME
    - docker container ls -a