stages:
  # - test
  # - lint
  # - build 
  - build
  - deploy

variables:
  IMAGE_NAME: lkslyj2/ops_docker
  CONTRAINER_NAME: docker-proj
    
# test:
#   stage: test
#   script:
#     - echo "TEST"

build:
  stage: build
  tags:
    - dockerrunner
  image: docker:latest
  services:
    - name: docker:dind
      alias: dockerdaemon
      command: ["--tls=false"]
  variables:
    # Tell docker CLI how to talk to Docker daemon.
    DOCKER_HOST: tcp://dockerdaemon:2375/
    # Use the overlayfs driver for improved performance.
    DOCKER_DRIVER: overlay2
    # Disable TLS since we're running inside local network.
    DOCKER_TLS_CERTDIR: ""
  script:
    - ls -al
    - docker container ls -a
    - docker build -t $IMAGE_NAME .
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
    - docker push $IMAGE_NAME
    - docker images
  only:
    - develop
    - main

deploy-dev:
  stage: deploy
  tags:
    - shellrunner
  variables:
    DEPLOY_PORT: "8001"
    MESSAGE: "PROD"
  script:
    - export SERVER_MESSAGE="$MESSAGE"
    - docker container ls -a
    - docker container rm $CONTRAINER_NAME-dev
    - docker run -d -p $DEPLOY_PORT:$DEPLOY_PORT --name $CONTRAINER_NAME-dev --restart always $IMAGE_NAME
    - docker container ls -a
  only:
    - develop

deploy-prod:
  stage: deploy
  tags:
    - shellrunner
  variables:
    DEPLOY_PORT: "8002"
    MESSAGE: "PROD"
  script:
    - export SERVER_MESSAGE="$MESSAGE"
    - docker container ls -a
    - docker container rm $CONTRAINER_NAME-prod
    - docker run -d -p $DEPLOY_PORT:$DEPLOY_PORT --name $CONTRAINER_NAME-prod --restart always $IMAGE_NAME
    - docker container ls -a
  only:
    - main